[[drone]]
id = 1
connected_node_ids = [2, 3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [1, 5]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [2, 6]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [3, 6]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [4, 5, 7]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [6, 8]
pdr = 0.05

[[client]]
id = 9
connected_drone_ids = [1]

[[server]]
id = 10
connected_drone_ids = [8]
