[[client]]
id = 1
connected_drone_ids = [3, 4]

[[drone]]
id = 2
connected_node_ids = [3, 4]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [1, 2, 5]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [1, 2, 6]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [3, 6, 7]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [4, 5, 8]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [5, 9, 10]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [6, 9, 10]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [7, 8]
pdr = 0.05

[[server]]
id = 10
connected_drone_ids = [7, 8]
