[[drone]]
id = 1
connected_node_ids = [2, 3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 5]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [1, 6, 7]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [2, 8]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [2, 9]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [3, 10]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [3, 11]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [4]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [5]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [6]
pdr = 0.05

[[drone]]
id = 11
connected_node_ids = [7]
pdr = 0.05

[[client]]
id = 12
connected_drone_ids = [8]

[[server]]
id = 13
connected_drone_ids = [11]
