[[client]]
id = 0
connected_drone_ids = [8]

[[server]]
id = 1
connected_drone_ids = [11]

[[drone]]
id = 2
connected_node_ids = [3, 4]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [2, 5, 6, 7]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [2, 5, 6, 7]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [3, 4, 8, 9, 10, 11]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [3, 4, 8, 9, 10, 11]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [3, 4, 8, 9, 10, 11]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [0, 5, 6, 7]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [5, 6, 7]
pdr = 0.0

[[drone]]
id = 10
connected_node_ids = [5, 6, 7]
pdr = 0.0

[[drone]]
id = 11
connected_node_ids = [1, 5, 6, 7]
pdr = 0.0

